package com.hdsx.hmglyh.webSeriviceTest.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CommonWebService service = new CommonWebService();
 * CommonWebService portType = service.getCommonWebServiceImplPort();
 * portType.getPractitionersRecognitionList(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CommonWebService", targetNamespace = "http://impl.service.bmds.com/", wsdlLocation = "http://120.236.163.198:58080/BMDS/WebService/getDate?wsdl")
public class CommonWebService_Service extends Service {

	private final static URL COMMONWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.hdsx.hmglyh.webSeriviceTest.service.CommonWebService_Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.hdsx.hmglyh.webSeriviceTest.service.CommonWebService_Service.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://120.236.163.198:58080/BMDS/WebService/getDate?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://120.236.163.198:58080/BMDS/WebService/getDate?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COMMONWEBSERVICE_WSDL_LOCATION = url;
	}

	public CommonWebService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CommonWebService_Service() {
		super(COMMONWEBSERVICE_WSDL_LOCATION, new QName(
				"http://impl.service.bmds.com/", "CommonWebService"));
	}

	/**
	 * 
	 * @return returns CommonWebService
	 */
	@WebEndpoint(name = "CommonWebServiceImplPort")
	public CommonWebService getCommonWebServiceImplPort() {
		return super.getPort(new QName("http://impl.service.bmds.com/",
				"CommonWebServiceImplPort"), CommonWebService.class);
	}

}
