
 var JiaoanssColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    {field:'spos',title:'起点桩号',width:100},
    {field:'epos',title:'止点桩号',width:100},
    {field:'sslx',title:'设施类型',width:100},
    {field:'sl',title:'数量',width:100},
    {field:'dw',title:'单位',width:100},
    {field:'gydw',title:'管养单位',width:100},
    {field:'szrq',title:'设置日期',width:100},
    { field: 'fx', title: '方向', width: 100 },
    {field:'szlxlx',title:'所在路线类型',width:100},
    {field:'bz',title:'备注',width:100}
]];
 var JiaotongbzColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
    { field: 'fx', title: '方向', width: 100 },
    {field:'pos',title:'桩号',width:100},
    {field:'sswz',title:'设置位置',width:100},
    {field:'bznr',title:'标志内容',width:100},
    {field:'bmcc',title:'版面尺寸',width:100},
    {field:'zcxs',title:'支撑形式',width:100},
    {field:'bzlb',title:'标志类别',width:100},
    {field:'szrq',title:'设置日期',width:100},
    {field:'gydw',title:'管养单位',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    {field:'bz',title:'备注',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100}
]];
 var TianqiaoColumns = [[
    {field:'roadcode',title:'路线代码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'code',title:'编码',width:100},
    {field:'name',title:'名称',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'pos',title:'中心桩号',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'kydwlx',title:'跨越地物类型',width:100},
    {field:'kydwmc',title:'跨越地物名称',width:100},
    {field:'kydegdwlx',title:'跨越第二地物类型',width:100},
    {field:'kydegdwmc',title:'跨越第二地物名称',width:100},
    {field:'sfxz',title:'收费性质',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'htlx',title:'互通类型',width:100},
    {field:'htjcfs',title:'互通交叉方式',width:100},
    {field:'htxs',title:'互通形式',width:100},
    {field:'qlcd',title:'桥梁长度',width:100},
    {field:'qlkjfl',title:'桥梁跨径分类',width:100},
    {field:'qlkjzc',title:'桥梁跨径总长',width:100},
    {field:'zqzk',title:'主桥主跨',width:100},
    {field:'zqks',title:'主桥孔数',width:100},
    {field:'kjzh',title:'跨径组合',width:100},
    {field:'qlxz',title:'桥梁性质',width:100},
    {field:'sjhz',title:'设计荷载',width:100},
    {field:'qmpzlx',title:'桥面铺装类型',width:100},
    {field:'sbjg',title:'上部结构',width:100},
 //   {field:'sbjgnb',title:'sbjgnb',width:100},
    {field:'qmqk',title:'桥面全宽',width:100},
    {field:'qmjk',title:'桥面净宽',width:100},
    {field:'qxjk',title:'桥下净空',width:100},
    {field:'kzdj',title:'抗震等级',width:100},
    {field:'thdj',title:'通航等级',width:100},
    {field:'qtlx',title:'桥台类型',width:100},
    {field:'qdlx',title:'桥墩类型',width:100},
    {field:'dtfzsslx',title:'墩台防撞设施类型',width:100},
    {field:'ssflx',title:'伸缩缝类型',width:100},
    {field:'zzlx',title:'支座类型',width:100},
    {field:'wpxtz',title:'弯坡斜特征',width:100},
    {field:'qlgd',title:'桥梁高度',width:100},
    {field:'rxdk',title:'人行道宽',width:100},
    {field:'jcsj',title:'建成时间',width:100},
    {field:'tcsj',title:'通车时间',width:100},
//    {field:'whnf2',title:'whnf2',width:100},
//    {field:'kjzh2',title:'kjzh2',width:100},
//    {field:'tz2',title:'tz2',width:100},
//    {field:'whnf3',title:'whnf3',width:100},
//    {field:'kjzh3',title:'kjzh3',width:100},
//    {field:'tz3',title:'tz3',width:100},
//    {field:'whnf4',title:'whnf4',width:100},
//    {field:'kjzh4',title:'kjzh4',width:100},
//    {field:'tz4',title:'tz4',width:100},
//    {field:'whnf5',title:'whnf5',width:100},
//    {field:'kjzh5',title:'kjzh5',width:100},
//    {field:'tz5',title:'tz5',width:100},
    {field:'bgyy',title:'变更原因',width:100},
    {field:'bgsj',title:'变更时间',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100},
    {field:'gjsj',title:'改建设计',width:100},
    {field:'jsxz',title:'建设性质',width:100},
    {field:'jsdw',title:'建设单位',width:100},
    {field:'sjdw',title:'设计单位',width:100},
    {field:'sgdw',title:'施工单位',width:100},
    {field:'jldw',title:'监理单位',width:100},
    {field:'zzj',title:'总造价',width:100},
    {field:'jspddj',title:'技术评定等级',width:100},
    {field:'pdrq',title:'评定日期',width:100},
    {field:'zjdqjcrq',title:'最近定期检查日期',width:100},
    {field:'zybhwz',title:'主要病害位置',width:100},
    {field:'bhms',title:'病害名称',width:100},
//    {field:'ycqdjtgzcs',title:'ycqdjtgzcs',width:100},
//    {field:'gydwxz',title:'gydwxz',width:100},
//    {field:'bhgzbw',title:'bhgzbw',width:100},
//    {field:'gzgcxz',title:'gzgcxz',width:100},
//    {field:'gzwgrq',title:'gzwgrq',width:100},
//    {field:'sfbbzxm',title:'sfbbzxm',width:100},
//    {field:'whnf1',title:'whnf1',width:100},
//    {field:'kjzh1',title:'kjzh1',width:100},
//    {field:'tz1',title:'tz1',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100}
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
]];

var fanghugcColumns = [[{field:'roadcode',title:'路线编号',rowspan:3,width:100,align:'center'},
    {field:'wz',title:'桩号',rowspan:3,width:100,align:'center'},
    {title:'上挡墙',width:100,align:'center',colspan:4},
    {title:'下挡墙',width:100,align:'center',colspan:4},
    {title:'浆砌块石',width:100,align:'center',colspan:4},
    {title:'水泥混凝土护坡',width:100,align:'center',colspan:4},
    {title:'浆砌边沟',width:100,align:'center',colspan:4},
    {title:'水泥边沟',width:100,align:'center',colspan:4},
    {title:'铁丝笼方格护坡',width:100,align:'center',colspan:4},
    {title:'砼方格网',width:100,align:'center',colspan:4},
    {title:'排水沟',width:100,align:'center',colspan:4},
    {title:'截水墙',width:100,align:'center',colspan:4},
    {title:'防落网',width:100,align:'center',colspan:2},
    {title:'拦水带',width:100,align:'center',colspan:4},
    {title:'急流槽',width:100,align:'center',colspan:2}],[
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'上护坡(米)',width:100,align:'center',colspan:4},
	{title:'下护坡(米)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(条)',width:100,align:'center',colspan:4},
	{title:'(条)',width:100,align:'center',colspan:4},
	{title:'(米)',width:100,align:'center',colspan:2},
	{title:'(米)',width:100,align:'center',colspan:4},
	{title:'(道)',width:100,align:'center',colspan:2}],[
	{title:'左',field:'sdbleft',width:100,align:'center'},
	{title:'材料',field:'sdblcl',width:100,align:'center'},
	{title:'右',field:'sdbright',width:100,align:'center'},
	{title:'材料',field:'sdbrcl',width:100,align:'center'},
	{title:'左',field:'xdbleft',width:100,align:'center'},
	{title:'材料',field:'xdblcl',width:100,align:'center'},
	{title:'右',field:'xdbright',width:100,align:'center'},
	{title:'材料',field:'xdbrcl',width:100,align:'center'},
	{title:'左',field:'jqksleft',width:100,align:'center'},
	{title:'材料',field:'jqkslcl',width:100,align:'center'},
	{title:'右',field:'jqksright',width:100,align:'center'},
	{title:'材料',field:'jqksrcl',width:100,align:'center'},
	{title:'左',field:'snhnthpleft',width:100,align:'center'},
	{title:'材料',field:'snhnthplcl',width:100,align:'center'},
	{title:'右',field:'snhnthpright',width:100,align:'center'},
	{title:'材料',field:'snhnthprcl',width:100,align:'center'},
	{title:'左',field:'jqbgleft',width:100,align:'center'},
	{title:'材料',field:'jqbglcl',width:100,align:'center'},
	{title:'右',field:'jqbgright',width:100,align:'center'},
	{title:'材料',field:'jqbgrcl',width:100,align:'center'},
	{title:'左',field:'snbgleft',width:100,align:'center'},
	{title:'材料',field:'snbglcl',width:100,align:'center'},
	{title:'右',field:'snbgright',width:100,align:'center'},
	{title:'材料',field:'snbgrcl',width:100,align:'center'},
	{title:'左',field:'tslfghpleft',width:100,align:'center'},
	{title:'材料',field:'tslfghplcl',width:100,align:'center'},
	{title:'右',field:'tslfghpright',width:100,align:'center'},
	{title:'材料',field:'tslfghprcl',width:100,align:'center'},
	{title:'左',field:'tfgwleft',width:100,align:'center'},
	{title:'材料',field:'tfgwlcl',width:100,align:'center'},
	{title:'右',field:'tfgwright',width:100,align:'center'},
	{title:'材料',field:'tfgwrcl',width:100,align:'center'},
	{title:'左',field:'psgleft',width:100,align:'center'},
	{title:'材料',field:'psglcl',width:100,align:'center'},
	{title:'右',field:'psgright',width:100,align:'center'},
	{title:'材料',field:'psgrcl',width:100,align:'center'},
	{title:'左',field:'jsqleft',width:100,align:'center'},
	{title:'材料',field:'jsqlcl',width:100,align:'center'},
	{title:'右',field:'jsqright',width:100,align:'center'},
	{title:'材料',field:'jsqrcl',width:100,align:'center'},
	{title:'左',field:'flwleft',width:100,align:'center'},
	{title:'右',field:'flwright',width:100,align:'center'},
	{title:'左',field:'lsdleft',width:100,align:'center'},
	{title:'材料',field:'lsdlcl',width:100,align:'center'},
	{title:'右',field:'lsdright',width:100,align:'center'},
	{title:'材料',field:'lsdrcl',width:100,align:'center'},
	{title:'左',field:'jlcleft',width:100,align:'center'},
	{title:'右',field:'jlcright',width:100,align:'center'}]];

var lumianbxColumns = [[{field:'roadcode',title:'路线编号',width:100},
    {field:'wz',title:'桩号',width:100},
    {field:'szlx',title:'设置类型',width:100},
    {field:'xtlx',title:'形态类型',width:100},
    {field:'bxfslx',title:'标线方式类型',width:100},
    {field:'bxkd',title:'标线宽度(m)',width:100},
    {field:'bxmj',title:'标线面积(㎡)',width:100},
    {field:'bxcl',title:'标线材料',width:100}]];

 var JianchazhanColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'桩号',width:100},
    {field:'jczlx',title:'检查站类型',width:100},
    {field:'jczwz',title:'检查站位置',width:100},
    {field:'jcnf',title:'建成年份',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'roadpos',title:'roadpos',width:100}
]];
 var JiaotonglianggczColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'桩号',width:100},
    {field:'jcnf',title:'建成年份',width:100},
    {field:'gczwz',title:'观测站位置',width:100},
    {field:'gczlx',title:'观测站类型',width:100},
    {field:'gcfs',title:'观测方式',width:100},
    {field:'gcqdzh',title:'观测起点桩号',width:100},
    {field:'dblcs',title:'代表里程数',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'npjrjtl',title:'年平均日交通量',width:100},
    {field:'tdxhcjdz',title:'特大型货车绝对值',width:100},
    {field:'dxhcjdz',title:'大型货车绝对值',width:100},
    {field:'zxhcjdz',title:'中型货车绝对值',width:100},
    {field:'xxhcjdz',title:'小型货车绝对值',width:100},
    {field:'tgcjdz',title:'拖挂车绝对值',width:100},
    {field:'dxkcjdz',title:'大型客车绝对值',width:100},
    {field:'xxkcjdz',title:'小型客车绝对值',width:100},
    {field:'tljjdz',title:'拖拉机绝对值',width:100},
    {field:'rlcjdz',title:'人力车绝对值',width:100},
    {field:'xlcjdz',title:'蓄力车绝对值',width:100},
    {field:'zxcjdz',title:'自行车绝对值',width:100},
    {field:'mtcjdz',title:'摩托车绝对值',width:100},
    {field:'jzxcjdz',title:'集装箱车绝对值',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'oId',title:'oId',width:100}
]];
 var LuxiandmtdColumns = [[
    {field:'roadcode',title:'路线代码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    { field: 'fx', title: '方向', width: 100 },
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'桩号',width:100},
    {field:'dmtddlx',title:'多媒体点类型',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'ms',title:'描述',width:100},
    {field:'dm',title:'地名',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'cId',title:'cId',width:100}
]];
 var FuwuquColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
//    {field:'code',title:'编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
    {field:'name',title:'名称',width:100},
//    {field:'fwqlx',title:'服务区类型',width:100},
    {field:'pos',title:'中心桩号',width:100},
    {field:'jcnf',title:'建成年月',width:100},
    {field:'zdmj',title:'占地面积',width:100},
    {field:'jzmj',title:'建筑面积',width:100},
    {field:'fwqwz',title:'服务区位置',width:100},
    {field:'ldlx',title:'路段类型',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
//    {field:'tbdwbm',title:'填报单位编码',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'tgzsfw',title:'提供住宿服务',width:100},
    {field:'tgqcjyfw',title:'提供汽车加油服务',width:100},
    {field:'tgqcxlfw',title:'提供汽车修理服务',width:100},
    {field:'tgcyfw',title:'提供餐饮服务',width:100},
    {field:'tgtcfw',title:'提供停车服务',width:100},
    {field:'tgcsfw',title:'提供超时服务',width:100},
//    {field:'fzr',title:'负责人',width:100},
//    {field:'lxdh',title:'联系电话',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'roadname',title:'roadname',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100}
]];
 var YanxianfwssColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
//    {field:'code',title:'编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
    {field:'name',title:'名称',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    { field: 'fx', title: '方向', width: 100 },
    { field: 'pos', title: '设施桩号', width: 100 },
    {field:'sslx',title:'设施类型',width:100},
    {field:'xdglwz',title:'相对公路位置',width:100},
    {field:'jcnf',title:'建成年份',width:100},
    {field:'ldlx',title:'路段类型',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
//    {field:'tbdwbm',title:'养护单位名称',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'dz',title:'地址',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100},
    {field:'bz',title:'备注',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'roadpos',title:'roadpos',width:100}
]];
 var ShoufeizhanColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
//    {field:'code',title:'编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'桩号',width:100},
    {field:'jcnf',title:'建成年份',width:100},
    {field:'zdmj',title:'占地面积',width:100},
    {field:'jzmj',title:'建筑面积',width:100},
    {field:'sfzlx',title:'收费站类型',width:100},
    {field:'ldlx',title:'路段类型',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
//    {field:'pzsfwjbh',title:'批准收费文件编号',width:100},
//    {field:'pzsfrq',title:'批准收费日期',width:100},
//    {field:'pzsfnx',title:'批准收费年限',width:100},
//    {field:'jssfsj',title:'结束收费时间',width:100},
    {field:'sfcds',title:'收费车道数',width:100},
    {field:'sfxz',title:'收费性质',width:100},
//    {field:'sffx',title:'收费方向',width:100},
//    {field:'yxygsfzjl',title:'与下一收费站距离',width:100},
//    {field:'gyzcszbl',title:'国有资产所占比例',width:100},
//    {field:'sfjglrys',title:'收费及管理人员数',width:100},
//    {field:'tzze',title:'投资总额',width:100},
//    {field:'hdye',title:'还贷余额',width:100},
//    {field:'dkje',title:'贷款金额',width:100},
//    {field:'lstdjm',title:'绿色通道减免',width:100},
//    {field:'qtjm',title:'其他减免',width:100},
//    {field:'nsfe',title:'年收费额',width:100},
//    {field:'nhde',title:'年还贷额',width:100},
//    {field:'yhjfzc',title:'养护经费支出',width:100},
//    {field:'qtfyzc',title:'其他费用支出',width:100},
//    {field:'tbdwbm',title:'填报单位编码',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'gydwxz',title:'管养单位性质',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100}
]];
 var GuanlijgColumns = [[
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'jglx',title:'机构类型',width:100},
    {field:'jcnf',title:'建成年份',width:100},
    {field:'zdmj',title:'占地面积',width:100},
    {field:'jzmj',title:'建筑面积',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'glgljgdz',title:'管路管理机构地址',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'yzbm',title:'邮政编码',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'zId',title:'zId',width:100}
]];
var YanghuzhanColumns = [[
	{field:'roadcode',title:'路线编码',width:100},
	{field:'name',title:'单位名称',width:100},
	{field:'code',title:'编码',width:100},
	{field:'xzqh',title:'行政区划',width:100},
	{field:'roadname',title:'路线名称',width:100},
    { field: 'fx', title: '方向', width: 100 },
	{field:'dwlx',title:'单位类型',width:100},
	{field:'pos',title:'所在桩号',width:100},
	{field:'jcnf',title:'建成年份',width:100},
	{field:'sswz',title:'设施位置',width:100},
	{field:'rybz',title:'人员编制',width:100},
	{field:'yhlc',title:'养护里程',width:100},
	{field:'scnl',title:'生产能力',width:100},
	{field:'zdmj',title:'占地面积',width:100},
	{field:'jzmj',title:'建筑面积',width:100},
	{field:'ldlx',title:'路段类型',width:100},
	{field:'zdbm',title:'匝道编码',width:100},
	{field:'dz',title:'地址',width:100},
	{field:'fzr',title:'负责人',width:100},
	{field:'lxdh',title:'联系电话',width:100},
//	{field:'tbdwbm',title:'填报单位编码',width:100},
//	{field:'gydwbm',title:'管养单位编码',width:100},
	{field:'gydwmc',title:'管养单位名称',width:100},
	{field:'bz',title:'备注',width:100},
	{field:'dsmc',title:'地市名称',width:100},
	{field:'qxmc',title:'区县名称',width:100},
	{field:'ptx',title:'ptx',width:100},
	{field:'pty',title:'pty',width:100},
	{field:'roadpos_',title:'roadpos_',width:100},
	{field:'roadpos',title:'roadpos',width:100},
	{field:'c_id',title:'c_id',width:100},
	{field:'m_ptx',title:'m_ptx',width:100},
	{field:'m_pty',title:'m_pty',width:100},
	{field:'z_id',title:'z_id',width:100},
	{field:'o_id',title:'o_id',width:100},
	{field:'id',title:'id',width:100},
	{field:'sfkbj',title:'sfkbj',width:100},
	{field:'fx',title:'方向',width:100}
]];

 
 
 
 
 
 
 
 
 
 
 
 