
var QiaoliangColumns = [[{title:'桥梁名称',width:100,rowspan:3,kid:'name'},
    {title:'编号',width:100,rowspan:3,kid:'code'},
    {title:'桥梁代码',width:100,rowspan:3},
    {title:'桥梁中心桩号',width:100,rowspan:3,kid:'pos'},
    {title:'所属路线情况',colspan:3},
    {title:'桥长',colspan:4},
    {title:'桥宽',colspan:2},
    {title:'桥梁分类',colspan:4},
    {title:'主桥上部结构',colspan:4},
    {title:'桥墩类型',colspan:2,rowspan:2},
    {title:'设计荷载等级',colspan:2,rowspan:2},
    {title:'抗震等级',colspan:2,rowspan:2},
    {title:'跨越地物',colspan:3,rowspan:2},
    {title:'通航等级',width:100,rowspan:3},
    {title:'墩台防撞设施类型',width:100,rowspan:3},
    {title:'是否互通立交',width:100,rowspan:3},
    {title:'建设情况',colspan:6},
    {title:'养护管理情况',colspan:5},
    {title:'技术状况评定情况',colspan:4},
    {title:'最近一次改造情况',colspan:6},
    {title:'当前主要病害',colspan:2,rowspan:2},
    {title:'交通管制措施',colspan:2,rowspan:2},
    {title:'所在政区代码',width:100,rowspan:3},
    {title:'备注',width:100,rowspan:3}],[
    {title:'路线编号',width:100,rowspan:2,kid:'roadcode'},
    {title:'路线名称',width:100,rowspan:2},
    {title:'技术等级',width:100,rowspan:2,kid:'jspddj'},
    {title:'桥梁全长(米)',width:100,rowspan:2,kid:'qlcd'},
    {title:'跨径总长(米)',width:100,rowspan:2,kid:'qlkjzc'},
    {title:'单孔最大跨径(米)',width:100,rowspan:2},
    {title:'跨径组合（孔*米）',width:100,rowspan:2},
    {title:'桥梁全宽（米）',width:100,rowspan:2},
    {title:'桥面净宽（米）',width:100,rowspan:2},
    {title:'按跨径分类',colspan:2},
    {title:'按使用年限分类',colspan:2},
    {title:'结构类型',colspan:2},
    {title:'材料',colspan:2},
    {title:'建设单位',width:100,rowspan:2},
    {title:'设计单位',width:100,rowspan:2},
    {title:'施工单位',width:100,rowspan:2},
    {title:'监理单位',width:100,rowspan:2},
    {title:'修建年度',width:100,rowspan:2},
    {title:'建成通车日期',width:100,rowspan:2},
    {title:'管养单位',colspan:2},
    {title:'监管单位名称',width:100,rowspan:2},
    {title:'收费性质',colspan:2},
    {title:'评定等级',colspan:2},
    {title:'评定日期',width:100,rowspan:2},
    {title:'评定单位',width:100,rowspan:2},
    {title:'改造年度',width:100,rowspan:2},
    {title:'完工日期',width:100,rowspan:2},
    {title:'改造部位',width:100,rowspan:2},
    {title:'工程性质',width:100,rowspan:2},
    {title:'改造施工单位',width:100,rowspan:2},
    {title:'是否部补助项目',width:100,rowspan:2}],[
    {title:'代码',width:100},
    {title:'类型',width:100},
    {title:'代码',width:100},
    {title:'类型',width:100},
    {title:'代码',width:100},
    {title:'类型',width:100},
    {title:'代码',width:100},
    {title:'名称',width:100},
    {title:'代码',width:100},
    {title:'类型',width:100},
    {title:'代码',width:100},
    {title:'等级',width:100},
    {title:'代码',width:100},
    {title:'等级',width:100},
    {title:'代码',width:100},
    {title:'类型',width:100},
    {title:'名称',width:100},
    {title:'单位性质',width:100},
    {title:'名称',width:100},
    {title:'代码',width:100},
    {title:'性质',width:100},
    {title:'代码',width:100},
    {title:'等级',width:100},
    {title:'部位',width:100},
    {title:'病害',width:100},
    {title:'代码',width:100},
    {title:'措施',width:100}],[
	{field:'name',title:'1',width:100},
	{field:'code',title:'2',width:100},
	{field:'code',title:'3',width:100},
	{field:'pos',title:'4',width:100},
	{field:'roadcode',title:'5',width:100},
	{field:'roadname',title:'6',width:100},
	{field:'jspddj',title:'7',width:100},
	{field:'qlcd',title:'8',width:100},
	{field:'qlkjzc',title:'9',width:100},
	{field:'zqzk',title:'10',width:100},
	{field:'kjzh',title:'11',width:110},
	{field:'qmqk',title:'12',width:100},
	{field:'qmjk',title:'13',width:100},
	{field:'a',title:'14',width:100,kid:"substr(qlkjfl,0,instr(qlkjfl,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.qlkjfl!=null && rowData.qlkjfl!='') return rowData.qlkjfl.split(".")[0]; else return '';}},
	{field:'b',title:'15',width:100,kid:"substr(qlkjfl,instr(qlkjfl,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.qlkjfl!=null && rowData.qlkjfl!='') return rowData.qlkjfl.split(".")[1]; else return '';}},
	{field:'null',title:'16',width:100},
	{field:'null',title:'17',width:100},
	{field:'c',title:'18',width:100,kid:"substr(sbjgnb,0,instr(sbjgnb,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.sbjgnb!=null && rowData.sbjgnb!='') return rowData.sbjgnb.split(".")[0]; else return '';}},
	{field:'d',title:'19',width:100,kid:"substr(sbjgnb,instr(sbjgnb,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.sbjgnb!=null && rowData.sbjgnb!='') return rowData.sbjgnb.split(".")[1]; else return '';}},
	{field:'e',title:'20',width:100,kid:"substr(qlsbjgcl,0,instr(qlsbjgcl,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.qlsbjgcl!=null && rowData.qlsbjgcl!='') return rowData.qlsbjgcl.split(".")[0]; else return '';}},
	{field:'f',title:'21',width:100,kid:"substr(qlsbjgcl,instr(qlsbjgcl,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.qlsbjgcl!=null && rowData.qlsbjgcl!='') return rowData.qlsbjgcl.split(".")[1]; else return '';}},
	{field:'g',title:'22',width:100,kid:"substr(qdlx,0,instr(qdlx,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.qdlx!=null && rowData.qdlx!='') return rowData.qdlx.split(".")[0]; else return '';}},
	{field:'h',title:'23',width:100,kid:"substr(qdlx,instr(qdlx,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.qdlx!=null && rowData.qdlx!='') return rowData.qdlx.split(".")[1]; else return '';}},
	{field:'i',title:'24',width:100,kid:"substr(sjhz,0,instr(sjhz,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.sjhz!=null && rowData.sjhz!='') return rowData.sjhz.split(".")[0]; else return '';}},
	{field:'j',title:'25',width:100,kid:"substr(sjhz,instr(sjhz,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.sjhz!=null && rowData.sjhz!='') return rowData.sjhz.split(".")[1]; else return '';}},
	{field:'k',title:'26',width:100,kid:"substr(kzdj,0,instr(kzdj,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.kzdj!=null && rowData.kzdj!='') return rowData.kzdj.split(".")[0]; else return '';}},
	{field:'l',title:'27',width:100,kid:"substr(kzdj,instr(kzdj,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.kzdj!=null && rowData.kzdj!='') return rowData.kzdj.split(".")[1]; else return '';}},
	{field:'m',title:'28',width:100,kid:"substr(kydwlx,0,instr(kydwlx,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.kydwlx!=null && rowData.kydwlx!='') return rowData.kydwlx.split(".")[0]; else return '';}},
	{field:'n',title:'29',width:100,kid:"substr(kydwlx,instr(kydwlx,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.kydwlx!=null && rowData.kydwlx!='') return rowData.kydwlx.split(".")[1]; else return '';}},
	{field:'kydwmc',title:'30',width:100},
	{field:'thdj',title:'31',width:100},
	{field:'dtfzsslx',title:'32',width:100},
	{field:'htlx',title:'33',width:100},
	{field:'jsdw',title:'34',width:100},
	{field:'sjdw',title:'35',width:100},
	{field:'sgdw',title:'36',width:100},
	{field:'jldw',title:'37',width:100},
	{field:'jcsj',title:'38',width:100},
	{field:'tcsj',title:'39',width:100},
	{field:'gydwxz',title:'40',width:100},
	{field:'gydwmc',title:'41',width:100},
	{field:'jgdwmc',title:'42',width:100},
	{field:'o',title:'43',width:100,kid:"substr(sfxz,0,instr(sfxz,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.sfxz!=null && rowData.sfxz!='') return rowData.sfxz.split(".")[0]; else return '';}},
	{field:'p',title:'44',width:100,kid:"substr(sfxz,instr(sfxz,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.sfxz!=null && rowData.sfxz!='') return rowData.sfxz.split(".")[1]; else return '';}},
	{field:'q',title:'45',width:100,kid:"substr(jspddj,0,instr(jspddj,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.jspddj!=null && rowData.jspddj!='') return rowData.jspddj.split(".")[0]; else return '';}},
	{field:'r',title:'46',width:100,kid:"substr(jspddj,instr(jspddj,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.jspddj!=null && rowData.jspddj!='') return rowData.jspddj.split(".")[1]; else return '';}},
	{field:'pdrq',title:'47',width:100},
	{field:'null',title:'48',width:100},
	{field:'gzwgrq',title:'49',width:100},
	{field:'gzwgrq',title:'50',width:100},
	{field:'bhgzbw',title:'51',width:100},
	{field:'gzgcxz',title:'52',width:100},
	{field:'null',title:'53',width:100},
	{field:'sfbbzxm',title:'54',width:100},
	{field:'zybhwz',title:'55',width:100},
	{field:'bhms',title:'56',width:100},
	{field:'ycqdjtgzcs',title:'57',width:100},
	{field:'ycqdjtgzcs',title:'58',width:100},
	{field:'xzqh',title:'59',width:100},
	{field:'bz',title:'60',width:100}]]; 



var Qiaoliang = [[
    {field:'roadcode',title:'路线代码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'name',title:'名称',width:100},
    {field:'yhzh',title:'养护桩号',width:100},
    {field:'pos',title:'中心桩号',width:100},
    {field:'kydwlx',title:'跨越地物类型',width:100},
    {field:'kydwmc',title:'跨越地物名称',width:100},
    {field:'kydwlx2',title:'跨越第二个地物类型',width:100},
    {field:'kydwmc2',title:'跨越第二个地物名称',width:100},
    {field:'sfxz',title:'收费性质',width:100},
    {field:'lxjsdj',title:'路线技术等级',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'jhlb',title:'计划类别',width:100},
    {field:'jhnd',title:'计划年度',width:100},
    {field:'jhwh',title:'计划文号',width:100},
    {field:'jhxmwybm',title:'计划项目唯一编码',width:100},
    {field:'jhxmlxbm',title:'计划项目路线编码',width:100},
    {field:'jhxmlxmc',title:'计划项目路线名称',width:100},
    {field:'jhxmzh',title:'计划项目桩号',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'htlx',title:'互通类型',width:100},
    {field:'htjcfs',title:'互通交叉方式',width:100},
    {field:'htxs',title:'互通形式',width:100},
    {field: 'qlcd', title: '桥梁长度', width: 100 },
    { field: 'qlkjfl', title: '桥梁跨径分类', width: 100 },
    {field:'qlkjzc',title:'桥梁跨径总长',width:100},
    {field:'zqzk',title:'主桥主跨',width:100},
    {field:'zqks',title:'主桥孔数',width:100},
    {field:'kjzh',title:'跨径组合',width:100},
    {field:'qlgd',title:'桥梁高度',width:100},
    
    {field:'qmqk',title:'桥面全宽',width:100},
    {field:'qmjk',title:'桥面净宽',width:100},
    {field:'qxjk',title:'桥下净宽',width:100},
    {field:'qmpzlx',title:'桥面铺装类型',width:100},
    {field:'qlsbjgcl',title:'桥梁上部结构材料',width:100},
    {field:'sbjg',title:'上部结构',width:100},
    {field:'sbjgnb',title:'上部结构（年报）',width:100},
    {field:'qlxz',title:'桥梁性质',width:100},
    {field:'sjhz',title:'设计荷载',width:100},
    {field:'kzdj',title:'抗震等级',width:100},
    {field:'thdj',title:'通航等级',width:100},
    {field:'qtlx',title:'桥台类型',width:100},
    {field:'qdlx',title:'桥墩类型',width:100},
    {field:'dtfzsslx',title:'墩台防撞设施类型',width:100},
    {field:'ssflx',title:'伸缩缝类型',width:100},
    {field:'zzlx',title:'支座类型',width:100},
    {field:'wpxtz',title:'弯坡斜特征',width:100},
    {field:'rxdk',title:'人行道宽',width:100},
    {field:'jcsj',title:'建成时间',width:100},
    {field:'tcsj',title:'通车时间',width:100},
    {field:'gjsj',title:'改建时间',width:100},
    {field:'jsxz',title:'建设性质',width:100},
    {field:'jsdw',title:'建设单位',width:100},
    {field:'sjdw',title:'设计单位',width:100},
    {field:'sgdw',title:'施工单位',width:100},
    {field:'jldw',title:'监理单位',width:100},
    {field:'zzj',title:'总造价',width:100},
    {field:'jspddj',title:'技术评定等级',width:100},
    {field:'pdrq',title:'评定日期',width:100},
    {field:'zjdqjcrq',title:'最近定期检查日期',width:100},
    {field:'zybhwz',title:'主要病害位置',width:100},
    {field:'bhms',title:'病害描述',width:100},
    {field:'ycqdjtgzcs',title:'已采取的交通管制措施',width:100},
    {field:'bhgzbw',title:'病害改造部位',width:100},
    {field:'gzgcxz',title:'改造工程性质',width:100},
    {field:'gzwgrq',title:'改造完工日期',width:100},
    {field:'sfbbzxm',title:'是否部补助项目',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwxz',title:'管养单位性质',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'jgdwmc',title:'监理单位名称',width:100},
//    {field:'whnf1',title:'whnf1',width:100},
//    {field:'kjzh1',title:'kjzh1',width:100},
//    {field:'tz1',title:'tz1',width:100},
//    {field:'whnf2',title:'whnf2',width:100},
//    {field:'kjzh2',title:'kjzh2',width:100},
//    {field:'tz2',title:'tz2',width:100},
//    {field:'whnf3',title:'whnf3',width:100},
//    {field:'kjzh3',title:'kjzh3',width:100},
//    {field:'tz3',title:'tz3',width:100},
//    {field:'whnf4',title:'whnf4',width:100},
//    {field:'kjzh4',title:'kjzh4',width:100},
//    {field:'tz4',title:'tz4',width:100},
//    {field:'whnf5',title:'whnf5',width:100},
//    {field:'kjzh5',title:'kjzh5',width:100},
//    {field:'tz5',title:'tz5',width:100},
    {field:'bgyy',title:'变更原因',width:100},
    {field:'bgsj',title:'变更时间',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100},
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'roadname',title:'roadname',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'dsfbm',title:'dsfbm',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100}
]];

var SuidaoColumns = [[{title:'隧道名称',width:100,rowspan:3,kid:'name'},
    {title:'隧道代码',width:100,rowspan:3,kid:'code'},
    {title:'所属路线情况',width:100,colspan:3},
    {title:'隧道中心桩号',width:100,rowspan:3,kid:'pos'},
    {title:'隧道长度（延米）',width:100,rowspan:3,kid:'sdcd'},
    {title:'隧道净宽（米）',width:100,rowspan:3,kid:'sdjk'},
    {title:'隧道净高（米）',width:100,rowspan:3,kid:'sdjg'},
    {title:'隧道按长度分类',width:100,rowspan:2,colspan:2},
    {title:'是否水下隧道',width:100,rowspan:3},
    {title:'建设情况',width:100,colspan:6},
    {title:'养护管理情况',width:100,colspan:3},
    {title:'技术状况评定情况',width:100,colspan:3},
    {title:'最近一次改造情况',width:100,colspan:4},
    {title:'当前主要病害',width:100,colspan:2},
    {title:'所在政区代码',width:100,rowspan:3},
    {title:'备注',width:100,rowspan:3}],[
    {title:'路线编号',width:100,rowspan:2,kid:'roadcode'},
    {title:'路线名称',width:100,rowspan:2},
    {title:'技术等级',width:100,rowspan:2},
    {title:'修建年度',width:100,rowspan:2},
    {title:'建设单位名称',width:100,rowspan:2},
    {title:'设计单位名称',width:100,rowspan:2},
    {title:'施工单位名称',width:100,rowspan:2},
    {title:'监理单位名称',width:100,rowspan:2},
    {title:'建成通车时间',width:100,rowspan:2},
    {title:'管养单位',width:100,colspan:2},
    {title:'监管单位名称',width:100,rowspan:2},
    {title:'评定等级',width:100,rowspan:2},
    {title:'评定日期',width:100,rowspan:2},
    {title:'评定单位',width:100,rowspan:2},
    {title:'改造年度',width:100,rowspan:2},
    {title:'完工日期',width:100,rowspan:2},
    {title:'改造部位',width:100,rowspan:2},
    {title:'工程性质',width:100,rowspan:2},
    {title:'病害部位',width:100,rowspan:2},
    {title:'病害描述',width:100,rowspan:2}],[
    {title:'代码',width:100},
    {title:'分类',width:100},
    {title:'单位性质代码',width:100},
    {title:'名称',width:100}],[
    {field:'name',title:'1',width:100},
    {field:'code',title:'2',width:100},
    {field:'roadcode',title:'3',width:100},
    {field:'roadname',title:'4',width:100},
    {field:'null',title:'5',width:100},
    {field:'pos',title:'6',width:100},
    {field:'sdcd',title:'7',width:100},
    {field:'sdjk',title:'8',width:100},
    {field:'sdjg',title:'9',width:100},
    {field:'a',title:'10',width:100,kid:"substr(sdfl,0,instr(sdfl,'.')-1)",formatter:function(value,rowData,rowIndex){if(rowData.sdfl!=null && rowData.sdfl!='') return rowData.sdfl.split(".")[0]; else return '';}},
    {field:'b',title:'11',width:100,kid:"substr(sdfl,instr(sdfl,'.')+1)",formatter:function(value,rowData,rowIndex){if(rowData.sdfl!=null && rowData.sdfl!='') return rowData.sdfl.split(".")[1]; else return '';}},
    {field:'sfsxsd',title:'12',width:100},
    {field:'jcsj',title:'13',width:100},
    {field:'jsdw',title:'14',width:100},
    {field:'sjdw',title:'15',width:100},
    {field:'sgdw',title:'16',width:100},
    {field:'jldw',title:'17',width:100},
    {field:'tcsj',title:'18',width:100},
    {field:'gydwxz',title:'19',width:100},
    {field:'gydwmc',title:'20',width:100},
    {field:'jgdwmc',title:'21',width:100},
    {field:'jspddj',title:'22',width:100},
    {field:'pdrq',title:'23',width:100},
    {field:'null',title:'24',width:100},
    {field:'gjrq',title:'25',width:100},
    {field:'gzwgrq',title:'26',width:100},
    {field:'bhgzbw',title:'27',width:100},
    {field:'gzgcxz',title:'28',width:100},
    {field:'zybhwz',title:'29',width:100},
    {field:'bhms',title:'30',width:100},
    {field:'xzqh',title:'31',width:100},
    {field:'bz',title:'32',width:100}]];




var Suidao = [[
    {field:'name',title:'名称',width:140},
    {field:'sdfl',title:'隧道分类',width:100},
    {field:'pos',title:'中心桩号',width:100},
    {field:'roadcode',title:'路线编码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'sfflssd',title:'是否分离式隧道',width:100},
    {field:'flssdsxxfx',title:'分离式隧道上下行方向',width:100},
    {field:'sfsxsd',title:'是否水下隧道',width:100},
    {field:'jhlb',title:'计划类别',width:100},
    {field:'jhnd',title:'计划年度',width:100},
    {field:'jhwh',title:'计划文号',width:100},
    {field:'jhxmwybm',title:'计划项目唯一编码',width:100},
    {field:'jhxmlxbm',title:'计划项目路线编码',width:100},
    {field:'jhxmlxmc',title:'计划项目路线名称',width:100},
    {field:'jhxmzh',title:'计划项目桩号',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'sdcd',title:'隧道长度',width:100},
    {field:'sdqk',title:'隧道全宽',width:100},
    {field:'sdjk',title:'隧道净宽',width:100},
    {field:'sdjg',title:'隧道净高',width:100},
    {field:'sdzm',title:'隧道照明',width:100},
    {field:'sdtf',title:'隧道通风',width:100},
    {field:'lmmclx',title:'路面面层类型',width:100},
    {field:'rxdk',title:'人行道宽',width:100},
    {field:'dkxs',title:'洞口形式',width:100},
    {field:'aqtds',title:'安全通道数',width:100},
    {field:'dzsb',title:'电子设备',width:100},
    {field:'dmxs',title:'断面形式',width:100},
    {field:'pslx',title:'排水类型',width:100},
    {field:'qccl',title:'砌衬材料',width:100},
    {field:'xfss',title:'消防设施',width:100},
    {field:'jcsj',title:'建成时间',width:100},
    {field:'tcsj',title:'通车时间',width:100},
    {field:'gjrq',title:'改建日期',width:100},
    {field:'jsxz',title:'建设性质',width:100},
    {field:'jsdw',title:'建设单位',width:100},
    {field:'sjdw',title:'设计单位',width:100},
    {field:'sgdw',title:'施工单位',width:100},
    {field:'jldw',title:'监理单位',width:100},
//    {field:'whnf1',title:'whnf1',width:100},
//    {field:'tz1',title:'tz1',width:100},
//    {field:'whnf2',title:'whnf2',width:100},
//    {field:'tz2',title:'tz2',width:100},
//    {field:'whnf3',title:'whnf3',width:100},
//    {field:'tz3',title:'tz3',width:100},
//    {field:'whnf4',title:'whnf4',width:100},
//    {field:'tz4',title:'tz4',width:100},
//    {field:'whnf5',title:'whnf5',width:100},
//    {field:'tz5',title:'tz5',width:100},
//    {field:'pdrq',title:'pdrq',width:100},
    {field:'jspddj',title:'技术评定等级',width:100},
    {field:'zybhwz',title:'主要病害位置',width:100},
    {field:'bhms',title:'病害描述',width:100},
    {field:'bhgzbw',title:'病害改造部位',width:100},
    {field:'gzgcxz',title:'改造工程性质',width:100},
    {field:'gzwgrq',title:'改造完工日期',width:100},
    {field:'jgdwmc',title:'监管单位名称',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'gydwxz',title:'管养单位性质',width:100},
    {field:'bgyy',title:'变更原因',width:100},
    {field:'bgsj',title:'变更时间',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100}
//    {field:'qxmc',title:'区县名称',width:100},
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
]];

var HandongColumns = [[
	{field:'roadcode',title:'路线编码',width:100},
	{field:'pos',title:'桩号',width:100},
	{field:'code',title:'涵洞编号',width:100},
	{field:'hdlx',title:'涵洞类型',width:100},
	{field:'jszk',title:'涵洞技术状况',width:100},
	{field:'ks',title:'孔数',width:100},
	{field:'kj',title:'孔径（米）',width:100},
	{field:'jk',title:'净跨（米）',width:100},
	{field:'hdqc',title:'涵洞全长（米）',width:100},
	{field:'jkxs',title:'进口形式',width:100},
	{field:'ckxs',title:'出口形式',width:100}]];

var Handong = [[
    {field:'roadcode',title:'路线编码',width:100},
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'roadname',title:'路线名称',width:100},
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'中心桩号',width:100},
    {field:'hdlx',title:'涵洞类型',width:100},
    {field:'ldlx',title:'路段类型',width:100},
    {field:'zdbm',title:'匝道编码',width:100},
    {field:'hdkj',title:'涵洞跨径',width:100},
    {field:'hdjg',title:'涵洞净高',width:100},
    {field:'hdcd',title:'涵洞长度',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'roadpos',title:'roadpos',width:100}
]];
 var LujifhColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    { field: 'fx', title: '方向', width: 100 },
    {field:'spos',title:'起点桩号',width:100},
    {field:'epos',title:'止点桩号',width:100},
    {field:'fhlx',title:'防护类型',width:100},
    {field:'gydw',title:'管养单位',width:100},
    {field:'szrq',title:'设置日期',width:100},
    {field:'bz',title:'备注',width:100}
]];