
 var GaosucrkColumns = [[
    {field:'roadcode',title:'路线编码',width:100,align:'center'},
//    {field:'xzqh',title:'行政区划',width:100},
//    {field:'code',title:'编码',width:100},
    {field:'roadname',title:'路线名称',width:100,align:'center'},
    {field:'crklx',title:'类型',width:100,align:'center'},
    {field:'pos',title:'桩号',width:100,align:'center'},
    {field:'crkwz',title:'位置',width:100,align:'center'},
    {field:'name',title:'出入口名称',width:100,align:'center'},
//    {field:'ldlx',title:'路段类型',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
//    {field:'cktwmdddm',title:'出口通往目的地地名',width:100},
    {field:'ljlxdm',title:'连接路线编号',width:100,align:'center'},
//    {field:'ljlxmc',title:'连接路线名称',width:100},
    {field:'ljlxzh',title:'连接路线桩号',width:100,align:'center'},
    {field:'cktwjqmc',title:'出口连接旅游景点',width:100,align:'center'},
//    {field:'qtzyxx',title:'其它重要信息',width:100},
//    {field:'tbdwbm',title:'填报单位编码',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
//    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'bz',title:'备注',width:100,align:'center'}
//    {field:'dsmc',title:'地市名称',width:100},
//    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'mPtx',title:'mPtx',width:100}
]];
 var PingjiaodkColumns = [[
//    {field:'pty',title:'pty',width:100},
    {field:'pos',title:'桩号',width:100,align:'center'},
    {field:'roadcode',title:'路线编号',width:100,align:'center'},
    {field:'roadname',title:'路线名称',width:100,align:'center'},
    {field:'gydwmc',title:'管养单位',width:100,align:'center'},
    {field:'jclkzl',title:'交叉路口种类',width:100,align:'center'},
//    {field:'jcxs',title:'交叉形式',width:100,align:'center'},
    {field:'1',title:'位置',width:100,align:'center',kid:'dsmc||qxmc',formatter:function(value,rowData,rowIndex){
    	return rowData.dsmc+" "+rowData.qxmc;
    }},
 	{field:'name',title:'名称',width:150,align:'center'},
//    {field:'code',title:'编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
//    {field:'ldlx',title:'路段类型',width:100},
//    {field:'roadcode2',title:'路线编码2',width:100},
//    {field:'lxzh2',title:'路线桩号2',width:100},
//    {field:'roadcode3',title:'路线编码3',width:100},
//    {field:'lxzh3',title:'路线桩号3',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'ptx',title:'ptx',width:100},
//    {field:'oId',title:'oId',width:100},
    {field:'bz',title:'备注',width:100,align:'center'}
//    {field:'zId',title:'zId',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'f002',title:'f002',width:100},
//    {field:'roadlevel',title:'roadlevel',width:100},
//    {field:'f070',title:'f070',width:100},
//    {field:'fbm',title:'fbm',width:100},
//    {field:'roadcode2D',title:'roadcode2D',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadcodeD',title:'roadcodeD',width:100},
//    {field:'roadcode',title:'roadcode',width:100},
//    {field:'qxmc',title:'区县名称',width:100},
//    {field:'dsmc',title:'地市名称',width:100},
//    {field:'tbdwbm',title:'养护单位',width:100},
//    {field:'roadpos2',title:'roadpos2',width:100}
]];