
 var DizhizhdColumns = [[
    {field:'roadcode',title:'路线编码',width:100},
//    {field:'code',title:'编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    { field: 'fx', title: '方向', width: 100 },
    {field:'name',title:'名称',width:100},
    {field:'pos',title:'位置桩号',width:100},
//    {field:'startzh',title:'起点桩号',width:100},
//    {field:'endzh',title:'止点桩号',width:100},
    {field:'yfdzzhdlx',title:'易发地质灾害的类型',width:100},
    {field:'ldlx',title:'路段类型',width:100},
//    {field:'ldcd',title:'路段长度',width:100},
//    {field:'zdbm',title:'匝道编码',width:100},
    {field:'tbdwbm',title:'养护单位名称',width:100},
//    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100},
    {field:'fx',title:'方向',width:100},
    {field:'bz',title:'备注',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'oId',title:'oId',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'roadpos',title:'roadpos',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100},
//    {field:'mPtx',title:'mPtx',width:100}
]];
   var ZaihaiyfldColumns = [[
     {field:'roadcode',title:'路线编码',width:100},
//     {field:'xzqh',title:'行政区划',width:100},
     {field:'roadname',title:'路线名称',width:100},
     {field:'wz',title:'位置桩号',width:100},
//     {field:'spos',title:'起点桩号',width:100},
//     {field:'epos',title:'止点桩号',width:100},
//     {field:'wz',title:'位置',width:100},
     {field:'yfzhlx',title:'易发灾害类型',width:100},
     {field:'ldlx',title:'路段类型',width:100},
     {field:'ldcd',title:'路段长度m',width:100},
     {field:'yhdwmc',title:'养护单位名称',width:100},
     {field:'gydwmc',title:'管养单位名称',width:100},
     {field:'dsmc',title:'地市名称',width:100},
     {field:'qxmc',title:'区县名称',width:100},
     {field:'fx',title:'方向',width:100},
     {field:'bz',title:'bz',width:100} 
]];
 var YingjibzdColumns = [[
    {field:'name',title:'名称',width:100},
    {field:'roadcode',title:'路线编码',width:100},
//    {field:'xzqh',title:'行政区划',width:100},
    { field: 'roadname', title: '路线名称', width: 100 },
    {field:'pos',title:'中心桩号',width:100},
    { field: 'dz', title: '地址', width: 100 },
    { field: 'zdmj', title: '占地面积', width: 100 },
    { field: 'jzmj', title: '建筑面积', width: 100 },
    { field: 'yjcljx', title: '应急车辆及机械', width: 100 },
    {field:'yjwzlx',title:'应急物资',width:100},
    { field: 'gydw', title: '管养单位', width: 100 },
    {field:'szrq',title:'设置日期',width:100},
    {field:'bz',title:'备注',width:100},
    { field: 'fx', title: '方向', width: 100 },
    { field: 'yhdw', title: '养护单位', width: 100 },
    { field: 'fzr', title: '负责人', width: 100 },
    { field: 'lxdh', title: '联系电话', width: 100 }
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100}
]];
 var WuzikuColumns = [[
    {field:'code',title:'编码',width:100},
    {field:'xzqh',title:'行政区划',width:100},
    {field:'name',title:'名称',width:100},
    {field:'lx',title:'类型',width:100},
    {field:'jcsj',title:'建成时间',width:100},
    {field:'wzzl',title:'物资种类',width:100},
    {field:'zdmj',title:'占地面积',width:100},
    {field:'jzmj',title:'建筑面积',width:100},
    {field:'lqkrl',title:'沥青库容量',width:100},
    {field:'bhcscnl',title:'拌和场生产能力',width:100},
    {field:'fzr',title:'负责人',width:100},
    {field:'lxdh',title:'联系电话',width:100},
    {field:'dz',title:'地址',width:100},
    {field:'tbdwbm',title:'填报单位编码',width:100},
    {field:'gydwbm',title:'管养单位编码',width:100},
    {field:'gydwmc',title:'管养单位名称',width:100},
    {field:'bz',title:'备注',width:100},
    {field:'dsmc',title:'地市名称',width:100},
    {field:'qxmc',title:'区县名称',width:100}
//    {field:'ptx',title:'ptx',width:100},
//    {field:'pty',title:'pty',width:100},
//    {field:'cId',title:'cId',width:100},
//    {field:'mPtx',title:'mPtx',width:100},
//    {field:'mPty',title:'mPty',width:100},
//    {field:'zId',title:'zId',width:100},
//    {field:'id',title:'id',width:100},
//    {field:'sfkbj',title:'sfkbj',width:100}
]];